<a href="https://colab.research.google.com/github/neklyud/pytorch-tutorial/blob/master/pytorch_tutorial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

In [0]:
x = torch.empty(5,3)
print(x)

tensor([[2.8056e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [6.5645e-07, 6.7010e-10, 6.6474e+22],
        [1.3385e+22, 2.5959e-09, 2.0920e+23],
        [6.4106e-10, 1.6503e-07, 0.0000e+00]])


In [0]:
x = torch.rand(5,3)
print(x)

tensor([[0.5872, 0.5097, 0.8370],
        [0.6919, 0.2689, 0.5285],
        [0.5613, 0.0672, 0.7533],
        [0.0717, 0.5340, 0.2139],
        [0.3562, 0.9497, 0.4128]])


In [0]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1007, -1.2935, -0.3261],
        [-0.5929,  0.6228,  0.2294],
        [ 0.1112,  0.2135,  0.8898],
        [-1.7136,  0.5455, -0.6849],
        [ 1.3768, -0.3985,  0.1559]])


In [0]:
print(x.size())

torch.Size([5, 3])


In [0]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 1.1187, -0.8680, -0.0582],
        [-0.2839,  0.6336,  1.0839],
        [ 0.5534,  0.4969,  0.9171],
        [-1.5291,  1.5366, -0.4730],
        [ 1.7355,  0.1822,  0.9165]])


In [0]:
print(torch.add(x,y))

tensor([[ 1.1187, -0.8680, -0.0582],
        [-0.2839,  0.6336,  1.0839],
        [ 0.5534,  0.4969,  0.9171],
        [-1.5291,  1.5366, -0.4730],
        [ 1.7355,  0.1822,  0.9165]])


In [0]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.1187, -0.8680, -0.0582],
        [-0.2839,  0.6336,  1.0839],
        [ 0.5534,  0.4969,  0.9171],
        [-1.5291,  1.5366, -0.4730],
        [ 1.7355,  0.1822,  0.9165]])


In [0]:
y.add_(x)
print(y)

tensor([[ 1.1187, -0.8680, -0.0582],
        [-0.2839,  0.6336,  1.0839],
        [ 0.5534,  0.4969,  0.9171],
        [-1.5291,  1.5366, -0.4730],
        [ 1.7355,  0.1822,  0.9165]])
tensor([[ 1.1007, -1.2935, -0.3261],
        [-0.5929,  0.6228,  0.2294],
        [ 0.1112,  0.2135,  0.8898],
        [-1.7136,  0.5455, -0.6849],
        [ 1.3768, -0.3985,  0.1559]])
tensor([[ 2.2194, -2.1615, -0.3844],
        [-0.8769,  1.2564,  1.3133],
        [ 0.6647,  0.7103,  1.8068],
        [-3.2427,  2.0821, -1.1580],
        [ 3.1123, -0.2164,  1.0724]])


In [0]:
print(x)
x.copy_(y)


tensor([[ 1.1007, -1.2935, -0.3261],
        [-0.5929,  0.6228,  0.2294],
        [ 0.1112,  0.2135,  0.8898],
        [-1.7136,  0.5455, -0.6849],
        [ 1.3768, -0.3985,  0.1559]])
tensor([[ 2.2194, -2.1615, -0.3844],
        [-0.8769,  1.2564,  1.3133],
        [ 0.6647,  0.7103,  1.8068],
        [-3.2427,  2.0821, -1.1580],
        [ 3.1123, -0.2164,  1.0724]])


In [0]:
print(x[1:2,2])

tensor([1.3133])


In [0]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.0822])
-0.08218337595462799


In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device = device)
  x = x.to(device)
  z = x + y
  print(z)
  print(z.to("cpu",torch.double))